### PR TITLE
use ray java snapshot version

### PR DESCRIPTION
**Pull request by kira-lin**
This PR creates a new branch to be compatible with Ray nightly, 2.0.0-dev. The ray jar version is still 1.1.0-SNAPSHOT because they didn't update the version for long, but it's actually 2.0.0-SNAPSHOT. I have submitted a PR there to update it.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
The memory unit has changed. You can refer here https://github.com/oap-project/raydp/pull/106/files

**Comment by ConeyLiu** [comment]
The ray 1.3.0 has released, should we just need to support ray 1.3.0 in the master branch?

**Comment by kira-lin** [comment]
I intended to have a branch which is compatible with ray-nightly. But if there is no need, we may just focus on 1.3.0.

**Comment by ConeyLiu** [comment]
Hi @kira-lin, should we merge this into the master branch first?

**Comment by kira-lin** [comment]
No, this PR is for 2.0.0. It's not compatible with 1.3.0, [`setJvmOptions`](https://github.com/ray-project/ray/blob/releases/1.3.0/java/api/src/main/java/io/ray/api/call/ActorCreator.java#L30) is not yet changed in 1.3.0.

**Pull request closed without merging**
