### PR TITLE
Two users cannot run their Spark driver on the same node and connect to the same Ray cluster.

### PR DESCRIPTION
**Pull request by Bowen0729**
https://github.com/oap-project/raydp/issues/175#issuecomment-1195190398

two users cannot run their Spark driver on the same node and connect to the same Ray cluster. 

Start the java gateway with a random port.

### CODE REVIEW

**Comment by carsonwang** [comment]
Thank you @Bowen0729 , can you please add a test for this?

**Comment by Bowen0729** [comment]
> Thank you @Bowen0729 , can you please add a test for this?

Hi, I have added a test for this.

**Comment by Bowen0729** [comment]
The CI is failed. What's the problem?

**Comment by carsonwang** [comment]
The CI is flaky these days. I just triggered a rerun of the failed test.

**Comment by Bowen0729** [comment]
I checked the CI log, and I find the Build and install step run mvn verify -q, not mvn clean package -q -DskipTests, so my test is always failed. What should I do?
@carsonwang

**Comment by Bowen0729** [comment]
@carsonwang Hi, I checked the CI log, the Build and install step run mvn verify -q, not the mvn clean package, the raydp jar seems not been compile with the new code, so the CI is always failed, am I right?

**Comment by Bowen0729** [comment]
@carsonwang My test is passed, other tests on macos error.

**Comment by carsonwang** [comment]
@Bowen0729 Previously I saw you tried to test running two spark drivers on the same node, that is the test we want to have. Is there any challenge to do that?

**Comment by Bowen0729** [comment]
> @Bowen0729 Previously I saw you tried to test running two spark drivers on the same node, that is the test we want to have. Is there any challenge to do that?

Yes, the test can passed in my mac, but cannot passed for the CI, I think I need some help.

**Comment by Bowen0729** [comment]
Sorry, I've been  a little busy recently, so I don't have time to solve this problem. Thanks for helping.

**Comment by kira-lin** [comment]
@carsonwang the test still hangs sometime. Shall we skip the tests?

**Comment by carsonwang** [comment]
Ok. Let's skip it for now. Does it also hangs sometime on your local machine?

**Comment by kira-lin** [comment]
yes, it hangs sometime and when I ctrl-c it, it shows popen_fork, even if I should have set start_method to spawn.

**Comment by carsonwang** [comment]
Thanks all! Merged

**Pull request merged**
