### PR TITLE
Support custom Spark location by picking up $SPARK_HOME

### PR DESCRIPTION
**Pull request by pang-wu**
This should address issue: https://github.com/oap-project/raydp/issues/250

The failed check will be fixed by [this PR](https://github.com/oap-project/raydp/pull/248).

### CODE REVIEW

**Comment by carsonwang** [comment]
Thanks @pang-wu . The change looks good. I'll see if we can fix the CI first and run the added test.

**Comment by pang-wu** [comment]
Thank you @carsonwang , one more thing though.. I can't seems to find a way to confirm in the test Spark is actually using the dir from `SPARK_HOME` rather than the on installed in python packages dir, do you mind to shred some light on that?

**Comment by carsonwang** [comment]
The Spark scripts like spark-submit will always check SPARK_HOME. Previously without this PR, if you have SPARK_HOME set, it will also use configurations under that directory. However it doesn't use the Spark jars under SPARK_HOME correctly. I think you can just test the Spark jar path and make sure it is using the correct one under SPARK_HOME.

**Comment by carsonwang** [comment]
LGTM. Thanks!

**Pull request merged**
