### PR TITLE
Add document about Ray autoscaling issue

### PR DESCRIPTION
**Pull request by carsonwang**
As suggested by @pang-wu , add the document about the Ray autoscaling issue.

### CODE REVIEW

**Comment by carsonwang** [comment]
@pang-wu , can you help take a look and see if there is anything missing here?

**Comment by pang-wu** [comment]
Thanks for changing this, maybe also reference the issue link: https://github.com/ray-project/ray/issues/20476 in the doc? @carsonwang

**Comment by carsonwang** [comment]
> Thanks for changing this, maybe also reference the issue link: [ray-project/ray#20476](https://github.com/ray-project/ray/issues/20476) in the doc? @carsonwang

Good suggestion. Just added the link.

**Comment by pang-wu** [comment]
👍 looks good to me

**Comment by DmitriGekhtman** [comment]
Fix being reviewed: https://github.com/ray-project/ray/pull/31202

**Comment by pang-wu** [comment]
Thanks @DmitriGekhtman, this will simplify our setup in our Spark usecases!

**Pull request merged**
