### PR TITLE
Support fetching kerberos delegation token

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by ConeyLiu** [comment]
Hi @zuston, thanks for the contribution. It breaks the lint check, could you fix it?

**Comment by zuston** [comment]
Fixed @ConeyLiu

**Comment by ConeyLiu** [comment]
Thanks @zuston

Hi @kira-lin, do you know why the CI is hanging?

**Comment by kira-lin** [comment]
Probably due to ray 1.4.0. I'll look into it. Please merge it and test again at that time. @zuston @ConeyLiu

**Comment by ConeyLiu** [comment]
Maybe, merged this.

**Comment by zuston** [comment]
Thanks @ConeyLiu

**Pull request merged**
