### PR TITLE
Set all spark conf when creating RayAppMaster

### PR DESCRIPTION
**Pull request by kira-lin**
This PR tries to solve #299 
Signed-off-by: Zhi Lin <zhi.lin@intel.com>

### CODE REVIEW

**Comment by carsonwang** [comment]
Can you please add a test?

**Comment by kira-lin** [comment]
we can't actually test the case in #299 because ci has only one node, and we've been testing ray client for every test. We can try to print spark conf to check spark.driver.host though.

**Comment by pang-wu** [comment]
Will this fix the bug when setting `spark.jars.packages` the jars won't be download in worker nodes?

**Comment by kira-lin** [comment]
> Will this fix the bug when setting spark.jars.packages the jars won't be download in worker nodes?

I think it won't, because this error occurs before the fault tolerance PR, but you can test it. Sorry we don't have enough bandwidth to look into it, I think we have a work-around for this, right?

**Comment by pang-wu** [comment]
Yeah correct, no worries.

**Pull request merged**
